
---
title: "02 Supervised ML"
author: "Rishon Noel Saldanha"
params:
  data_dir: "../../data/"
---

Load the absolute path to the data directory.

```{r}
data_dir <- params$data_dir
```

# Libraries
```{r}
library(tidymodels)
library(tidyverse)
library(recipes)
library(rsample)
library(yardstick)
```

# Data
```{r}
bike_features_tbl <- readRDS("C:/Users/risho/OneDrive/Desktop/internship_sparks/ss24-bdml-rishon1234/ML/data/Business Decisions with Machine Learning/bike_features_tbl.rds")
bike_features_tbl |> as_tibble() |> print()
```

Transform dataset
```{r}
bike_features_trafo_tbl <- bike_features_tbl %>% 
    select(model:url, `Rear Derailleur`, `Shift Lever`) %>%
    mutate_if(is.numeric, ~replace(., is.na(.), 0)) %>%
    mutate(id = row_number()) %>% 
    select(id, everything(), -url)
bike_features_trafo_tbl |> as_tibble() |> print()
```

Create training and testing dataset (Hold-out method)
```{r}
bike_features_trafo_tbl %>% distinct(category_2) %>% print()

set.seed(123)
split <- initial_split(bike_features_trafo_tbl, prop = 3/4, strata = "category_2")

split %>% training() %>% distinct(category_2) %>% print()
split %>% testing() %>% distinct(category_2) %>% print()

train_tbl <- training(split)
test_tbl  <- testing(split)

train_tbl <- train_tbl %>% set_names(str_replace_all(names(train_tbl), " |-", "_"))
test_tbl  <- test_tbl  %>% set_names(str_replace_all(names(test_tbl),  " |-", "_"))
```





# Visualization
```{r}
g1 <- bike_features_trafo_tbl %>% 
    mutate(category_2 = as.factor(category_2) %>% 
           fct_reorder(price)) %>% 
    
    ggplot(aes(category_2, price)) +
    geom_violin() +
    geom_jitter(width = 0.1, alpha = 0.5, color = "#2dc6d6") +
    coord_flip() +
    facet_wrap(~ frame_material) +
    scale_y_continuous(labels = scales::dollar_format()) +
    labs(
        title = "Unit Price for Each Model",
        y = "", x = "Category 2"
    )
g1
```
